apiVersion: v1
kind: Service
metadata:
  labels:
    app: meu-nginx
  name: meu-nginx
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32333
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: meu-nginx
  sessionAffinity: None
  type: LoadBalancer
