apiVersion: batch/v1
kind: CronJob
metadata:
  name: giropops-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: giropops-cron
              image: busybox
              args:
              - /bin/sh
              - giropops-cron
              - date; echo Bem Vindo ao Descomplicando Kubernetes - Bora Will ; sleep 30
          restartPolicy: OnFailure